import NextAuthProvider from "@/providers/NextAuthProvider";
import "./globals.css";
import { yekan } from "@/utils/fonts";

export const metadata = {
  title: "EyeSun Smart Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
